basePath: /
definitions:
  github_com_eerzho_telegram_ai_pkg_sse.Event:
    properties:
      data:
        type: string
      id:
        type: integer
      name:
        type: string
      retry:
        description: milliseconds
        type: integer
    type: object
  httpjson.Error:
    properties:
      code:
        type: string
      details:
        items:
          $ref: '#/definitions/httpjson.ErrorDetail'
        type: array
      message:
        type: string
    type: object
  httpjson.ErrorDetail:
    properties:
      code:
        type: string
      field:
        type: string
      message:
        type: string
    type: object
  internal_improvement_improvement_generate.Input:
    properties:
      text:
        minLength: 1
        type: string
    required:
    - text
    type: object
  internal_monitoring_health_check.Output:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
  internal_response_response_generate.Input:
    properties:
      language:
        maxLength: 2
        minLength: 2
        type: string
      messages:
        items:
          $ref: '#/definitions/internal_response_response_generate.InputMessage'
        maxItems: 1000
        minItems: 1
        type: array
      owner:
        $ref: '#/definitions/internal_response_response_generate.InputUser'
    required:
    - language
    - messages
    - owner
    type: object
  internal_response_response_generate.InputMessage:
    properties:
      date:
        type: integer
      sender:
        $ref: '#/definitions/internal_response_response_generate.InputUser'
      text:
        minLength: 1
        type: string
    required:
    - date
    - sender
    - text
    type: object
  internal_response_response_generate.InputUser:
    properties:
      chat_id:
        minLength: 1
        type: string
      name:
        minLength: 1
        type: string
    required:
    - chat_id
    - name
    type: object
  internal_summary_summary_generate.Input:
    properties:
      language:
        maxLength: 2
        minLength: 2
        type: string
      messages:
        items:
          $ref: '#/definitions/internal_summary_summary_generate.InputMessage'
        maxItems: 1000
        minItems: 1
        type: array
      owner:
        $ref: '#/definitions/internal_summary_summary_generate.InputUser'
    required:
    - language
    - messages
    - owner
    type: object
  internal_summary_summary_generate.InputMessage:
    properties:
      date:
        type: integer
      sender:
        $ref: '#/definitions/internal_summary_summary_generate.InputUser'
      text:
        minLength: 1
        type: string
    required:
    - date
    - sender
    - text
    type: object
  internal_summary_summary_generate.InputUser:
    properties:
      chat_id:
        minLength: 1
        type: string
      name:
        minLength: 1
        type: string
    required:
    - chat_id
    - name
    type: object
externalDocs:
  description: GitHub
  url: https://github.com/eerzho/telegram_ai
host: localhost
info:
  contact: {}
  description: Telegram with AI features
  title: TelegramAI
  version: "1.0"
paths:
  /_hc:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_monitoring_health_check.Output'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: health check
      tags:
      - monitoring
  /v1/improvements/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_improvement_improvement_generate.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: improvement generate
      tags:
      - improvement
  /v1/responses/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_response_response_generate.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: response generate
      tags:
      - response
  /v1/summaries/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_summary_summary_generate.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: summary generate
      tags:
      - summary
schemes:
- http
swagger: "2.0"
