basePath: /
definitions:
  github_com_eerzho_telegram_ai_pkg_sse.Event:
    properties:
      data:
        type: string
      id:
        type: integer
      name:
        type: string
      retry:
        description: milliseconds
        type: integer
    type: object
  httpjson.Error:
    properties:
      code:
        type: string
      details:
        items:
          $ref: '#/definitions/httpjson.ErrorDetail'
        type: array
      message:
        type: string
    type: object
  httpjson.ErrorDetail:
    properties:
      code:
        type: string
      field:
        type: string
      message:
        type: string
    type: object
  internal_improvement_generate_improvement.Input:
    properties:
      text:
        minLength: 1
        type: string
    required:
    - text
    type: object
  internal_monitoring_health_check.Output:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
  internal_response_generate_response.Input:
    properties:
      language:
        maxLength: 2
        minLength: 2
        type: string
      messages:
        items:
          $ref: '#/definitions/internal_response_generate_response.InputMessage'
        maxItems: 1000
        minItems: 1
        type: array
      owner:
        $ref: '#/definitions/internal_response_generate_response.InputUser'
    required:
    - language
    - messages
    - owner
    type: object
  internal_response_generate_response.InputMessage:
    properties:
      date:
        type: integer
      sender:
        $ref: '#/definitions/internal_response_generate_response.InputUser'
      text:
        minLength: 1
        type: string
    required:
    - date
    - sender
    - text
    type: object
  internal_response_generate_response.InputUser:
    properties:
      chat_id:
        type: integer
      name:
        minLength: 1
        type: string
    required:
    - chat_id
    - name
    type: object
  internal_setting_create_setting.Input:
    properties:
      chat_id:
        type: integer
      style:
        maxLength: 500
        type: string
      user_id:
        type: integer
    required:
    - chat_id
    - user_id
    type: object
  internal_setting_create_setting.Output:
    properties:
      chat_id:
        type: integer
      created_at:
        type: string
      style:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  internal_setting_get_setting.Output:
    properties:
      chat_id:
        type: integer
      created_at:
        type: string
      style:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  internal_setting_update_setting.Input:
    properties:
      style:
        maxLength: 500
        type: string
    type: object
  internal_setting_update_setting.Output:
    properties:
      chat_id:
        type: integer
      created_at:
        type: string
      style:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  internal_summary_generate_summary.Input:
    properties:
      language:
        maxLength: 2
        minLength: 2
        type: string
      messages:
        items:
          $ref: '#/definitions/internal_summary_generate_summary.InputMessage'
        maxItems: 1000
        minItems: 1
        type: array
      owner:
        $ref: '#/definitions/internal_summary_generate_summary.InputUser'
    required:
    - language
    - messages
    - owner
    type: object
  internal_summary_generate_summary.InputMessage:
    properties:
      date:
        type: integer
      sender:
        $ref: '#/definitions/internal_summary_generate_summary.InputUser'
      text:
        minLength: 1
        type: string
    required:
    - date
    - sender
    - text
    type: object
  internal_summary_generate_summary.InputUser:
    properties:
      chat_id:
        type: integer
      name:
        minLength: 1
        type: string
    required:
    - chat_id
    - name
    type: object
externalDocs:
  description: GitHub
  url: https://github.com/eerzho/telegram_ai
host: localhost
info:
  contact: {}
  description: Telegram with AI features
  title: TelegramAI
  version: "1.0"
paths:
  /_hc:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_monitoring_health_check.Output'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: health check
      tags:
      - monitoring
  /v1/improvements/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_improvement_generate_improvement.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: improvement generate
      tags:
      - improvement
  /v1/responses/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_response_generate_response.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: response generate
      tags:
      - response
  /v1/settings:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_setting_create_setting.Input'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_setting_create_setting.Output'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: create setting
      tags:
      - setting
  /v1/settings/{user_id}/{chat_id}:
    delete:
      parameters:
      - description: UserID
        in: path
        name: user_id
        required: true
        type: integer
      - description: ChatID
        in: path
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: delete setting
      tags:
      - setting
    get:
      parameters:
      - description: UserID
        in: path
        name: user_id
        required: true
        type: integer
      - description: ChatID
        in: path
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_setting_get_setting.Output'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: get setting
      tags:
      - setting
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_setting_update_setting.Input'
      - description: UserID
        in: path
        name: user_id
        required: true
        type: integer
      - description: ChatID
        in: path
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_setting_update_setting.Output'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: update setting
      tags:
      - setting
  /v1/summaries/generate:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_summary_generate_summary.Input'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_eerzho_telegram_ai_pkg_sse.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpjson.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpjson.Error'
      summary: summary generate
      tags:
      - summary
schemes:
- http
swagger: "2.0"
